#!/bin/sh

DAEMON_PATH=/home/root/server/aesdsocket   # <-- update this path to your compiled aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid

case "$1" in
  start)
    echo "Starting $DAEMON_NAME..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- -d
    ;;
  stop)
    echo "Stopping $DAEMON_NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 5
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      echo "$DAEMON_NAME is running with PID $(cat $PIDFILE)"
    else
      echo "$DAEMON_NAME is not running"
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

